### ISSUE TITLE
Typo: Should be N <= H <= G instead of N <= G <= G

### ISSUE THREAD

**Issue by correcthorsebatterystaple** [jTanG0506/uom-cheat-sheets#9]
https://github.com/jTanG0506/uom-cheat-sheets/blob/3184b76341b542aeb514e6f2afe5242d3562f8a9/third-year/math32001/math32001.tex#L353

**Comment by jTanG0506** [comment]
Fixed fa98702f52666afa82f0e7b682b86093c8dae7a0, thanks!
